use std::path::{Path, PathBuf};

use baobao_codegen::FileBuilder;
use baobao_core::{FileRules, GeneratedFile, Overwrite};

use crate::{Fn, RustFileBuilder};

const GENERATED_HEADER: &str = "// Generated by Bao - DO NOT EDIT";

/// The app.rs file that handles Context setup and CLI dispatch
pub struct AppRs {
    pub is_async: bool,
}

impl AppRs {
    pub fn new(is_async: bool) -> Self {
        Self { is_async }
    }

    fn build_run_fn(&self) -> Fn {
        let body = if self.is_async {
            "let ctx = Context::new().await?;\nCli::parse().dispatch(&ctx).await"
        } else {
            "let ctx = Context::new()?;\nCli::parse().dispatch(&ctx)"
        };

        let mut f = Fn::new("run").returns("eyre::Result<()>").body(body);

        if self.is_async {
            f = f.async_();
        }

        f
    }
}

impl GeneratedFile for AppRs {
    fn path(&self, base: &Path) -> PathBuf {
        base.join("src").join("app.rs")
    }

    fn rules(&self) -> FileRules {
        FileRules {
            overwrite: Overwrite::Always,
            header: Some(GENERATED_HEADER),
        }
    }

    fn render(&self) -> String {
        FileBuilder::rust()
            .add_import("clap", "Parser")
            .add_import("crate::context", "Context")
            .add_import("crate::generated", "Cli")
            .with_code(|c| self.build_run_fn().render(c))
            .render_rust_with_header(GENERATED_HEADER)
    }
}
