use std::path::{Path, PathBuf};

use baobao_core::{FileRules, GeneratedFile, Overwrite};

use crate::{Fn, RustFile, Use};

const GENERATED_HEADER: &str = "// Generated by Bao - DO NOT EDIT";

/// The app.rs file that handles Context setup and CLI dispatch
pub struct AppRs {
    pub is_async: bool,
}

impl AppRs {
    pub fn new(is_async: bool) -> Self {
        Self { is_async }
    }

    fn build_run_fn(&self) -> Fn {
        let await_suffix = if self.is_async { ".await" } else { "" };
        let body = format!(
            "let ctx = Context::new(){}?;\nCli::parse().dispatch(&ctx){}",
            await_suffix, await_suffix
        );

        Fn::new("run")
            .returns("eyre::Result<()>")
            .body(body)
            .async_if(self.is_async)
    }
}

impl GeneratedFile for AppRs {
    fn path(&self, base: &Path) -> PathBuf {
        base.join("src").join("app.rs")
    }

    fn rules(&self) -> FileRules {
        FileRules {
            overwrite: Overwrite::Always,
            header: Some(GENERATED_HEADER),
        }
    }

    fn render(&self) -> String {
        RustFile::new()
            .use_stmt(Use::new("clap").symbol("Parser"))
            .use_stmt(Use::new("crate::context").symbol("Context"))
            .use_stmt(Use::new("crate::generated").symbol("Cli"))
            .add(self.build_run_fn())
            .render_with_header(GENERATED_HEADER)
    }
}
