use std::path::{Path, PathBuf};

use baobao_core::{FileRules, GeneratedFile, Overwrite};

/// The app.rs file that handles Context setup and CLI dispatch
pub struct AppRs {
    pub is_async: bool,
}

impl AppRs {
    pub fn new(is_async: bool) -> Self {
        Self { is_async }
    }
}

impl GeneratedFile for AppRs {
    fn path(&self, base: &Path) -> PathBuf {
        base.join("src").join("app.rs")
    }

    fn rules(&self) -> FileRules {
        FileRules {
            overwrite: Overwrite::Always,
            header: Some("// Generated by Bao - DO NOT EDIT\n\n"),
        }
    }

    fn render(&self) -> String {
        if self.is_async {
            r#"use clap::Parser;

use crate::context::Context;
use crate::generated::Cli;

pub async fn run() -> eyre::Result<()> {
    let ctx = Context::new().await?;
    Cli::parse().dispatch(&ctx).await
}
"#
            .to_string()
        } else {
            r#"use clap::Parser;

use crate::context::Context;
use crate::generated::Cli;

pub fn run() -> eyre::Result<()> {
    let ctx = Context::new()?;
    Cli::parse().dispatch(&ctx)
}
"#
            .to_string()
        }
    }
}
