use std::path::{Path, PathBuf};

use baobao_core::{FileRules, GeneratedFile, Overwrite, to_snake_case};

use crate::{RawCode, RustFile};

const GENERATED_HEADER: &str = "// Generated by Bao - DO NOT EDIT";

/// A generated command `commands/{name}.rs` file containing args struct and optional subcommand dispatch
pub struct CommandRs {
    pub name: String,
    pub content: String,
}

impl CommandRs {
    pub fn new(name: impl Into<String>, content: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            content: content.into(),
        }
    }
}

impl GeneratedFile for CommandRs {
    fn path(&self, base: &Path) -> PathBuf {
        // Use snake_case for file names (handles dashed names like "my-command" -> "my_command")
        let file_name = to_snake_case(&self.name);
        base.join("src")
            .join("generated")
            .join("commands")
            .join(format!("{}.rs", file_name))
    }

    fn rules(&self) -> FileRules {
        FileRules {
            overwrite: Overwrite::Always,
            header: Some(GENERATED_HEADER),
        }
    }

    fn render(&self) -> String {
        RustFile::new()
            .add(RawCode::new(&self.content))
            .render_with_header(GENERATED_HEADER)
    }
}
