use std::path::{Path, PathBuf};

use baobao_core::{FileRules, GeneratedFile, Overwrite, to_snake_case};

const GENERATED_HEADER: &str = "// Generated by Bao - DO NOT EDIT\n\n";

/// The commands/mod.rs file that exports all command modules
pub struct CommandsMod {
    pub commands: Vec<String>,
}

impl CommandsMod {
    pub fn new(commands: Vec<String>) -> Self {
        Self { commands }
    }
}

impl GeneratedFile for CommandsMod {
    fn path(&self, base: &Path) -> PathBuf {
        base.join("src")
            .join("generated")
            .join("commands")
            .join("mod.rs")
    }

    fn rules(&self) -> FileRules {
        FileRules {
            overwrite: Overwrite::Always,
            header: Some(GENERATED_HEADER),
        }
    }

    fn render(&self) -> String {
        let mut out = String::new();

        // Add header
        out.push_str(GENERATED_HEADER);

        // Convert command names to snake_case for Rust module names
        // (handles dashed names like "my-command" -> "my_command")
        for name in &self.commands {
            let module_name = to_snake_case(name);
            out.push_str(&format!("pub mod {};\n", module_name));
        }
        out.push('\n');
        for name in &self.commands {
            let module_name = to_snake_case(name);
            out.push_str(&format!("pub use {}::*;\n", module_name));
        }

        out
    }
}
