use std::path::{Path, PathBuf};

use baobao_core::{FileRules, GeneratedFile, Overwrite};

const GENERATED_HEADER: &str = "// Generated by Bao - DO NOT EDIT\n\n";

/// A generated command `commands/{name}.rs` file containing args struct and optional subcommand dispatch
pub struct CommandRs {
    pub name: String,
    pub content: String,
}

impl CommandRs {
    pub fn new(name: impl Into<String>, content: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            content: content.into(),
        }
    }
}

impl GeneratedFile for CommandRs {
    fn path(&self, base: &Path) -> PathBuf {
        base.join("src")
            .join("generated")
            .join("commands")
            .join(format!("{}.rs", self.name))
    }

    fn rules(&self) -> FileRules {
        FileRules {
            overwrite: Overwrite::Always,
            header: Some(GENERATED_HEADER),
        }
    }

    fn render(&self) -> String {
        let mut out = String::new();

        // Add header
        out.push_str(GENERATED_HEADER);
        out.push_str(&self.content);

        out
    }
}
