use std::path::{Path, PathBuf};

use baobao_core::{FileRules, GeneratedFile, Overwrite};

const GENERATED_HEADER: &str = "// Generated by Bao - DO NOT EDIT\n\n";

/// The generated/mod.rs file that exports the CLI and commands
pub struct GeneratedMod;

impl GeneratedFile for GeneratedMod {
    fn path(&self, base: &Path) -> PathBuf {
        base.join("src").join("generated").join("mod.rs")
    }

    fn rules(&self) -> FileRules {
        FileRules {
            overwrite: Overwrite::Always,
            header: Some(GENERATED_HEADER),
        }
    }

    fn render(&self) -> String {
        let mut out = String::new();

        // Add header
        out.push_str(GENERATED_HEADER);

        out.push_str("pub mod cli;\n");
        out.push_str("pub mod commands;\n\n");
        out.push_str("pub use cli::*;\n");

        out
    }
}
