[package]
name = "bao"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "bao"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
bao-client = { workspace = true }
bao-core = { workspace = true }
bao-daemon = { workspace = true }
bao-transport = { workspace = true }
bao-tui = { workspace = true }
clap = { version = "4", features = ["derive"] }
crossterm = { workspace = true }
dirs = "5"
tokio = { workspace = true }

[dev-dependencies]
bao-client = { workspace = true }
bao-core = { workspace = true }
tokio = { workspace = true }
bao-protocol = { workspace = true }

[lints]
workspace = true
