//! cli.ts generator for TypeScript projects using boune.

use std::path::{Path, PathBuf};

use baobao_codegen::{CodeBuilder, CommandInfo};
use baobao_core::{FileRules, GeneratedFile, Overwrite, Version, to_camel_case, to_kebab_case};

use crate::ast::{Const, Import, MethodChain};

const GENERATED_HEADER: &str = "// Generated by Bao - DO NOT EDIT";

/// The cli.ts file containing the main CLI setup using boune.
pub struct CliTs {
    pub name: String,
    pub version: Version,
    pub description: Option<String>,
    pub commands: Vec<CommandInfo>,
}

impl CliTs {
    pub fn new(
        name: impl Into<String>,
        version: Version,
        description: Option<String>,
        commands: Vec<CommandInfo>,
    ) -> Self {
        Self {
            name: name.into(),
            version,
            description,
            commands,
        }
    }

    fn render_imports(&self, builder: CodeBuilder) -> CodeBuilder {
        let builder = Import::new("boune").named("cli").render(builder);

        self.commands.iter().fold(builder, |b, cmd| {
            let camel = to_camel_case(&cmd.name);
            let file = to_kebab_case(&cmd.name);
            Import::new(format!("./commands/{}.ts", file))
                .named(format!("{}Command", camel))
                .render(b)
        })
    }

    fn build_cli_chain(&self) -> String {
        let mut chain = MethodChain::new("cli")
            .arg(format!("\"{}\"", self.name))
            .call("version", format!("\"{}\"", self.version))
            .call_opt(
                "description",
                self.description.as_ref().map(|d| format!("\"{}\"", d)),
            );

        for cmd in &self.commands {
            let camel = to_camel_case(&cmd.name);
            chain = chain.call("command", format!("{}Command", camel));
        }

        format!("{};", chain.build())
    }

    fn render_cli_setup(&self, builder: CodeBuilder) -> CodeBuilder {
        let builder = builder.blank();
        Const::new("app", self.build_cli_chain()).render(builder)
    }
}

impl GeneratedFile for CliTs {
    fn path(&self, base: &Path) -> PathBuf {
        base.join("src").join("cli.ts")
    }

    fn rules(&self) -> FileRules {
        FileRules {
            overwrite: Overwrite::Always,
            header: Some(GENERATED_HEADER),
        }
    }

    fn render(&self) -> String {
        let builder = CodeBuilder::typescript().line(GENERATED_HEADER);
        let builder = self.render_imports(builder);
        let builder = self.render_cli_setup(builder);
        builder.build()
    }
}
