//! cli.ts generator for TypeScript projects using boune.

use std::path::{Path, PathBuf};

use baobao_codegen::schema::CommandInfo;
use baobao_core::{FileRules, GeneratedFile, Overwrite, Version, to_camel_case, to_kebab_case};

use crate::{
    ast::{Const, Import},
    code_file::{CodeFile, RawCode},
};

const GENERATED_HEADER: &str = "// Generated by Bao - DO NOT EDIT";

/// The cli.ts file containing the main CLI setup using boune.
pub struct CliTs {
    pub name: String,
    pub version: Version,
    pub description: Option<String>,
    pub commands: Vec<CommandInfo>,
}

impl CliTs {
    pub fn new(
        name: impl Into<String>,
        version: Version,
        description: Option<String>,
        commands: Vec<CommandInfo>,
    ) -> Self {
        Self {
            name: name.into(),
            version,
            description,
            commands,
        }
    }

    fn build_imports(&self) -> Vec<Import> {
        let mut imports = vec![Import::new("boune").named("defineCli")];

        for cmd in &self.commands {
            let camel = to_camel_case(&cmd.name);
            let file = to_kebab_case(&cmd.name);
            imports.push(
                Import::new(format!("./commands/{}.ts", file)).named(format!("{}Command", camel)),
            );
        }

        imports
    }

    fn build_cli_schema(&self) -> String {
        let mut schema = String::new();
        schema.push_str("defineCli({\n");
        schema.push_str(&format!("  name: \"{}\",\n", self.name));
        schema.push_str(&format!("  version: \"{}\",\n", self.version));

        if let Some(desc) = &self.description {
            schema.push_str(&format!("  description: \"{}\",\n", desc));
        }

        // Commands object
        schema.push_str("  commands: {\n");
        for cmd in &self.commands {
            let camel = to_camel_case(&cmd.name);
            schema.push_str(&format!("    {}: {}Command,\n", camel, camel));
        }
        schema.push_str("  },\n");

        schema.push_str("})");
        schema
    }
}

impl GeneratedFile for CliTs {
    fn path(&self, base: &Path) -> PathBuf {
        base.join("src").join("cli.ts")
    }

    fn rules(&self) -> FileRules {
        FileRules {
            overwrite: Overwrite::Always,
            header: Some(GENERATED_HEADER),
        }
    }

    fn render(&self) -> String {
        let file = CodeFile::new()
            .add(RawCode::new(GENERATED_HEADER))
            .imports(self.build_imports())
            .add(Const::new("app", self.build_cli_schema()));

        file.render()
    }
}
