//! Individual command file generator for TypeScript projects.

use std::path::{Path, PathBuf};

use baobao_core::{FileRules, GeneratedFile, Overwrite, to_kebab_case};

const GENERATED_HEADER: &str = "// Generated by Bao - DO NOT EDIT\n\n";

/// A generated command `commands/{name}.ts` file.
pub struct CommandTs {
    pub name: String,
    pub content: String,
}

impl CommandTs {
    pub fn new(name: impl Into<String>, content: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            content: content.into(),
        }
    }
}

impl GeneratedFile for CommandTs {
    fn path(&self, base: &Path) -> PathBuf {
        // Use kebab-case for TypeScript file names
        let file_name = to_kebab_case(&self.name);
        base.join("src")
            .join("commands")
            .join(format!("{}.ts", file_name))
    }

    fn rules(&self) -> FileRules {
        FileRules {
            overwrite: Overwrite::Always,
            header: Some(GENERATED_HEADER),
        }
    }

    fn render(&self) -> String {
        let mut out = String::new();
        out.push_str(GENERATED_HEADER);
        out.push_str(&self.content);
        out
    }
}
