//! context.ts generator for TypeScript projects.

use std::path::{Path, PathBuf};

use baobao_codegen::{CodeBuilder, ContextFieldInfo};
use baobao_core::{ContextFieldType, DatabaseType, FileRules, GeneratedFile, Overwrite};

use crate::ast::{Field, Import, ObjectType};

const GENERATED_HEADER: &str = "// Generated by Bao - DO NOT EDIT";

/// The context.ts file containing shared application state.
pub struct ContextTs {
    pub fields: Vec<ContextFieldInfo>,
}

impl ContextTs {
    pub fn new(fields: Vec<ContextFieldInfo>) -> Self {
        Self { fields }
    }

    fn needs_sqlite(&self) -> bool {
        self.fields.iter().any(|f| {
            matches!(
                f.field_type,
                ContextFieldType::Database(DatabaseType::Sqlite)
            )
        })
    }

    fn render_imports(&self, builder: CodeBuilder) -> CodeBuilder {
        if self.needs_sqlite() {
            Import::new("bun:sqlite")
                .named("Database")
                .render(builder)
                .blank()
        } else {
            builder
        }
    }

    fn render_context_type(&self, builder: CodeBuilder) -> CodeBuilder {
        let mut context = ObjectType::new("Context");

        for field in &self.fields {
            let ts_type = match &field.field_type {
                ContextFieldType::Database(DatabaseType::Sqlite) => "Database",
                ContextFieldType::Database(DatabaseType::Postgres) => "unknown",
                ContextFieldType::Database(DatabaseType::Mysql) => "unknown",
                ContextFieldType::Http => "unknown",
            };
            context = context.field(Field::new(&field.name, ts_type));
        }

        context.render(builder)
    }
}

impl GeneratedFile for ContextTs {
    fn path(&self, base: &Path) -> PathBuf {
        base.join("src").join("context.ts")
    }

    fn rules(&self) -> FileRules {
        FileRules {
            overwrite: Overwrite::Always,
            header: Some(GENERATED_HEADER),
        }
    }

    fn render(&self) -> String {
        let builder = CodeBuilder::typescript().line(GENERATED_HEADER).blank();
        let builder = self.render_imports(builder);
        let builder = self.render_context_type(builder);
        builder.build()
    }
}
