//! TypeScript file generators.

/// Header marker for generated files that should not be manually edited.
pub const GENERATED_HEADER: &str = "// Generated by Bao - DO NOT EDIT";

mod cli_ts;
mod command_ts;
mod context_ts;
mod gitignore;
mod handler_ts;
mod index_ts;
mod package_json;
mod tsconfig;

pub use baobao_codegen::generation::BaoToml;
pub use cli_ts::CliTs;
pub use command_ts::CommandTs;
pub use context_ts::ContextTs;
pub use gitignore::GitIgnore;
pub use handler_ts::{HandlerTs, STUB_MARKER};
pub use index_ts::IndexTs;
pub use package_json::{Dependency, PackageJson};
pub use tsconfig::TsConfig;
