[package]
name = "bao-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
bao-core = { workspace = true }
bao-protocol = { workspace = true }
bao-transport = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
